"""Comprehensive tests for ModelGateway usage telemetry semantics, cost calculation, and health caching."""

import pytest
import pytest_asyncio
from contextlib import asynccontextmanager
from unittest.mock import AsyncMock, MagicMock
from uuid import uuid4
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

from ai.gateway.model_gateway import ModelGateway
from ai.providers.base import LLMProvider
from ai.providers.router import ModelRouter
from ai.registry.model_registry import ModelDefinition, ModelRegistry
from ai.registry.provider_registry import ProviderRegistry
from ai.schemas import LLMRequest, LLMResponse, ModelCapability, ProviderHealth
from database.connection import Base
from database.models.user import User as DBUser
from database.repositories.user_repo import UserRepository
from database.repositories.usage_repo import UsageRepository
from shared.exceptions import ProviderError, ProviderUnavailableError


class ControllableMockLLM(LLMProvider):
    def __init__(self, name: str, models: list[str], should_fail: bool = False, tokens: int = 150):
        self._name = name
        self._models = models
        self._should_fail = should_fail
        self._tokens = tokens
        self.health_check_called_count = 0
        self._capabilities = [ModelCapability.REASONING]

    @property
    def name(self) -> str:
        return self._name

    @property
    def models(self) -> list[str]:
        return self._models

    @property
    def is_local(self) -> bool:
        return True

    @property
    def capabilities(self) -> list[ModelCapability]:
        return self._capabilities

    async def complete(self, request: LLMRequest) -> LLMResponse:
        if self._should_fail:
            raise ProviderError(self.name, "Connection timed out")

        prompt_tok = self._tokens // 2
        comp_tok = self._tokens - prompt_tok
        return LLMResponse(
            content=f"Generated by {self.name}",
            model=request.model or self._models[0],
            usage={"prompt_tokens": prompt_tok, "completion_tokens": comp_tok, "total_tokens": self._tokens},
        )

    async def stream_complete(self, request: LLMRequest):
        yield "token"

    async def health_check(self) -> ProviderHealth:
        self.health_check_called_count += 1
        return ProviderHealth(provider=self.name, healthy=not self._should_fail)


@pytest_asyncio.fixture
async def db_session_maker():
    engine = create_async_engine("sqlite+aiosqlite:///:memory:", echo=False)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    session_maker = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    @asynccontextmanager
    async def session_factory():
        async with session_maker() as session:
            try:
                yield session
                await session.commit()
            except Exception:
                await session.rollback()
                raise

    yield session_factory, session_maker
    await engine.dispose()


@pytest.mark.asyncio
async def test_usage_semantics_single_success_one_record_and_accurate_cost(db_session_maker):
    session_factory, session_maker = db_session_maker

    # Create user
    async with session_maker() as session:
        user = DBUser(username="test_user", email="user@example.com", password_hash="hash")
        await UserRepository(session).create(user)
        await session.commit()
        user_id = user.id

    model_reg = ModelRegistry()
    model_reg.register(
        ModelDefinition(
            model_id="gpt-custom",
            provider_name="custom-prov",
            capabilities={ModelCapability.REASONING},
            input_cost=0.005,   # $5 per 1M tokens = $0.005 per 1K tokens
            output_cost=0.015,  # $15 per 1M tokens = $0.015 per 1K tokens
            priority=10,
        )
    )

    prov_reg = ProviderRegistry()
    # Prompt tokens = 500, Completion tokens = 500
    prov_reg.register_llm(ControllableMockLLM("custom-prov", ["gpt-custom"], tokens=1000))

    router = ModelRouter(model_registry=model_reg, provider_registry=prov_reg)
    gateway = ModelGateway(
        router=router,
        model_registry=model_reg,
        provider_registry=prov_reg,
        session_factory=session_factory,
    )

    req = LLMRequest(
        messages=[{"role": "user", "content": "Hello"}],
        metadata={"user_id": str(user_id)},
    )
    resp = await gateway.complete(req)

    # Cost = (0.005 / 1000 * 500) + (0.015 / 1000 * 500) = 0.0025 + 0.0075 = 0.0100
    expected_cost = (0.005 / 1000 * 500) + (0.015 / 1000 * 500)
    assert abs(resp.metadata["cost_usd"] - expected_cost) < 1e-6

    # Verify exactly ONE UsageRecord exists in DB
    async with session_maker() as session:
        records = await UsageRepository(session).get_user_usage(user_id)
        assert len(records) == 1
        assert records[0].success is True
        assert records[0].total_tokens == 1000
        assert abs(records[0].cost_usd - expected_cost) < 1e-6


@pytest.mark.asyncio
async def test_usage_semantics_fallback_success_records_only_successful_model(db_session_maker):
    session_factory, session_maker = db_session_maker

    async with session_maker() as session:
        user = DBUser(username="fallback_user", email="fb@example.com", password_hash="hash")
        await UserRepository(session).create(user)
        await session.commit()
        user_id = user.id

    model_reg = ModelRegistry()
    model_reg.register(
        ModelDefinition(
            model_id="primary-failing-model",
            provider_name="failing-prov",
            capabilities={ModelCapability.REASONING},
            priority=20,
        )
    )
    model_reg.register(
        ModelDefinition(
            model_id="secondary-success-model",
            provider_name="success-prov",
            capabilities={ModelCapability.REASONING},
            priority=10,
        )
    )

    prov_reg = ProviderRegistry()
    prov_reg.register_llm(ControllableMockLLM("failing-prov", ["primary-failing-model"], should_fail=True))
    prov_reg.register_llm(ControllableMockLLM("success-prov", ["secondary-success-model"], should_fail=False))

    router = ModelRouter(model_registry=model_reg, provider_registry=prov_reg)
    gateway = ModelGateway(
        router=router,
        model_registry=model_reg,
        provider_registry=prov_reg,
        session_factory=session_factory,
    )

    req = LLMRequest(
        model="primary-failing-model",
        messages=[{"role": "user", "content": "Hello"}],
        metadata={"user_id": str(user_id)},
    )
    resp = await gateway.complete(req)

    assert resp.model == "secondary-success-model"
    assert resp.metadata["fallback_occurred"] is True

    # Check DB: Exactly ONE record for the successful fallback model, NO success record for failing provider
    async with session_maker() as session:
        records = await UsageRepository(session).get_user_usage(user_id)
        assert len(records) == 1
        assert records[0].model == "secondary-success-model"
        assert records[0].provider == "success-prov"
        assert records[0].success is True


@pytest.mark.asyncio
async def test_usage_semantics_all_providers_fail_no_successful_record(db_session_maker):
    session_factory, session_maker = db_session_maker

    async with session_maker() as session:
        user = DBUser(username="fail_user", email="fail@example.com", password_hash="hash")
        await UserRepository(session).create(user)
        await session.commit()
        user_id = user.id

    model_reg = ModelRegistry()
    model_reg.register(ModelDefinition(model_id="m1", provider_name="p1", capabilities={ModelCapability.REASONING}))

    prov_reg = ProviderRegistry()
    prov_reg.register_llm(ControllableMockLLM("p1", ["m1"], should_fail=True))

    router = ModelRouter(model_registry=model_reg, provider_registry=prov_reg)
    gateway = ModelGateway(
        router=router,
        model_registry=model_reg,
        provider_registry=prov_reg,
        session_factory=session_factory,
    )

    req = LLMRequest(
        model="m1",
        messages=[{"role": "user", "content": "Hello"}],
        metadata={"user_id": str(user_id)},
    )

    with pytest.raises(Exception):
        await gateway.complete(req)

    # Check DB: Zero successful records created
    async with session_maker() as session:
        records = await UsageRepository(session).get_user_usage(user_id)
        assert len(records) == 0


@pytest.mark.asyncio
async def test_usage_semantics_zero_token_success(db_session_maker):
    session_factory, session_maker = db_session_maker

    async with session_maker() as session:
        user = DBUser(username="zero_tok", email="zero@example.com", password_hash="hash")
        await UserRepository(session).create(user)
        await session.commit()
        user_id = user.id

    model_reg = ModelRegistry()
    model_reg.register(ModelDefinition(model_id="zero-m", provider_name="zero-p", capabilities={ModelCapability.REASONING}))

    prov_reg = ProviderRegistry()
    prov_reg.register_llm(ControllableMockLLM("zero-p", ["zero-m"], tokens=0))

    router = ModelRouter(model_registry=model_reg, provider_registry=prov_reg)
    gateway = ModelGateway(
        router=router,
        model_registry=model_reg,
        provider_registry=prov_reg,
        session_factory=session_factory,
    )

    req = LLMRequest(messages=[{"role": "user", "content": "Hi"}], metadata={"user_id": str(user_id)})
    resp = await gateway.complete(req)

    assert resp.metadata["total_tokens"] == 0

    async with session_maker() as session:
        records = await UsageRepository(session).get_user_usage(user_id)
        assert len(records) == 1
        assert records[0].total_tokens == 0
        assert records[0].cost_usd == 0.0


@pytest.mark.asyncio
async def test_db_persistence_failure_does_not_corrupt_or_fail_ai_response():
    # Broken session factory that raises exception
    @asynccontextmanager
    async def broken_session_factory():
        raise RuntimeError("Database connection pool exhausted")
        yield None

    model_reg = ModelRegistry()
    model_reg.register(ModelDefinition(model_id="resilient-m", provider_name="resilient-p", capabilities={ModelCapability.REASONING}))

    prov_reg = ProviderRegistry()
    prov_reg.register_llm(ControllableMockLLM("resilient-p", ["resilient-m"]))

    router = ModelRouter(model_registry=model_reg, provider_registry=prov_reg)
    gateway = ModelGateway(
        router=router,
        model_registry=model_reg,
        provider_registry=prov_reg,
        session_factory=broken_session_factory,
    )

    req = LLMRequest(messages=[{"role": "user", "content": "Hi"}], metadata={"user_id": str(uuid4())})
    # Must NOT raise exception despite DB failure
    resp = await gateway.complete(req)
    assert resp.content == "Generated by resilient-p"


@pytest.mark.asyncio
async def test_health_cache_no_health_check_on_every_routing():
    model_reg = ModelRegistry()
    model_reg.register(
        ModelDefinition(
            model_id="m1",
            provider_name="p1",
            capabilities={ModelCapability.REASONING, ModelCapability.EXTRACTION, ModelCapability.SUMMARIZATION},
        )
    )

    prov_reg = ProviderRegistry()
    mock_prov = ControllableMockLLM("p1", ["m1"])
    prov_reg.register_llm(mock_prov)

    # Initial explicit health check caches health
    await prov_reg.health_check_all()
    assert mock_prov.health_check_called_count == 1

    router = ModelRouter(model_registry=model_reg, provider_registry=prov_reg)

    # Perform 10 routing decisions
    for _ in range(10):
        model_def, provider = router.select_model_and_provider(task="research")
        assert model_def.model_id == "m1"
        assert provider.name == "p1"

    # Health check count must remain 1 (no network calls during routing)
    assert mock_prov.health_check_called_count == 1
