"""Pydantic schemas and domain models for Adversarial Multi-Agent Debates."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class DebateConfig(BaseModel):
    """Configuration parameters for an adversarial debate session."""

    topic: str
    initial_thesis: str
    counter_thesis: Optional[str] = None
    max_rounds: int = Field(default=3, ge=1, le=10)
    proposer_model: str = "gemini-2.5-pro"
    opposer_model: str = "gemini-2.5-pro"
    arbiter_model: str = "gemini-2.5-pro"
    k_factor: float = Field(default=32.0, description="Elo sensitivity K-factor")


class ArgumentCitation(BaseModel):
    """Citation or evidence grounding for a debate argument."""

    source_id: Optional[str] = None
    title: str
    url: Optional[str] = None
    snippet: str
    reliability: float = 1.0


class ArgumentTurn(BaseModel):
    """A single argument turn generated by either the Proposer or Opposer."""

    agent_role: str  # "proposer" or "opposer"
    argument_text: str
    key_claims: List[str] = Field(default_factory=list)
    citations: List[ArgumentCitation] = Field(default_factory=list)
    persuasiveness_score: float = Field(default=0.0, ge=0.0, le=1.0)
    concessions_made: List[str] = Field(default_factory=list)


class RoundCritique(BaseModel):
    """Arbiter evaluation for a single debate round."""

    round_number: int
    round_winner: str  # "proposer", "opposer", or "draw"
    critique: str
    proposer_score: float = Field(ge=0.0, le=1.0)
    opposer_score: float = Field(ge=0.0, le=1.0)
    elo_delta: float = 0.0
    proposer_elo_after: float = 1500.0
    opposer_elo_after: float = 1500.0


class ClaimEloDelta(BaseModel):
    """Elo adjustment for a specific debated claim."""

    claim_text: str
    initial_elo: float = 1500.0
    final_elo: float = 1500.0
    delta: float = 0.0
    status: str = "undecided"  # "accepted", "refuted", "contested"


class DebateConsensusPayload(BaseModel):
    """Synthesized consensus produced by the Consensus Arbiter."""

    consensus_statement: str
    accepted_claims: List[Dict[str, Any]] = Field(default_factory=list)
    refuted_claims: List[Dict[str, Any]] = Field(default_factory=list)
    concessions: List[Dict[str, Any]] = Field(default_factory=list)
    remaining_uncertainties: List[str] = Field(default_factory=list)
    overall_confidence: float = Field(ge=0.0, le=1.0)
    winner_overall: str = "balanced_consensus"
    proposer_final_elo: float = 1500.0
    opposer_final_elo: float = 1500.0
    synthesis_metadata: Dict[str, Any] = Field(default_factory=dict)
